baseURL: "https://pydatakl.github.io/"
languageCode: "en-us"
title: "kualalumpur.py"
theme: "papermod"
params:
    homeInfoParams:
        Title: PyData Kuala Lumpur
        Content: Can be Info, links, about...

    socialIcons: # optional
        - name: twitter
          url: https://twitter.com/pydatakl
        - name: github
          url: https://github.com/PyDataKL
